# Generated by Django 4.0.dev20210712094637 on 2021-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0007_remove_ad_clicks_remove_ad_views_view_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='viewID',
        ),
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Click',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
