# Generated by Django 4.0.dev20210712094637 on 2021-07-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0008_remove_view_viewid_ad_clicks_ad_views_delete_click_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ip', models.GenericIPAddressField()),
                ('viewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_mangement.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ip', models.GenericIPAddressField()),
                ('adID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_mangement.ad')),
            ],
        ),
    ]
