# Generated by Django 4.0.dev20210712094637 on 2021-07-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0010_ad_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
