# Generated by Django 4.0.dev20210715050039 on 2021-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0016_alter_ad_advertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='imgUrl',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
