# Generated by Django 4.0.dev20210715050039 on 2021-07-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0017_alter_ad_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='imgUrl',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='click',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
