# Generated by Django 4.0.dev20210715050039 on 2021-07-21 11:21

import advertiser_mangement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0018_alter_ad_imgurl_alter_click_date_alter_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='imgUrl',
            field=models.ImageField(upload_to=advertiser_mangement.models.upload_to, verbose_name='Image'),
        ),
    ]
