# Generated by Django 4.0.dev20210715050039 on 2021-07-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0019_alter_ad_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='summaryShit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('adID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mySummary', to='advertiser_mangement.ad')),
            ],
        ),
    ]
