# Generated by Django 4.0.dev20210715050039 on 2021-07-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0020_summaryshit'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryshit',
            name='view_or_click',
            field=models.IntegerField(choices=[(0, 'Click'), (1, 'View')], default=1),
        ),
    ]
