# Generated by Django 4.0.dev20210712094637 on 2021-07-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0011_alter_click_date_alter_view_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
    ]
