# Generated by Django 4.0.dev20210715050039 on 2021-07-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0013_view_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='a',
        ),
    ]
