# Generated by Django 4.0.dev20210715050039 on 2021-07-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0014_remove_view_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='adID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myClicks', to='advertiser_mangement.ad'),
        ),
        migrations.AlterField(
            model_name='view',
            name='viewID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myViews', to='advertiser_mangement.ad'),
        ),
    ]
