# Generated by Django 4.0.dev20210715050039 on 2021-07-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0015_alter_click_adid_alter_view_viewid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='myAds', to='advertiser_mangement.advertiser'),
        ),
    ]
